### ISSUE TITLE
Feature request: reverse results

### ISSUE THREAD

**Issue by jgresty** [jarun/ddgr#100]
Usually the most reinvent search results are at the top of the list, however when using a small terminal this can be scrolled out of view. It would be really helpful for an option to display the results in reverse order so the most reinvent results are near the cursor.

**Comment by jarun** [comment]
I have considered this but looking at the current code it seems to be too much of work without much ROI. When we reverse results, we also need to take care of reversing the indices, ranges etc. when opening in browser. At this stage of the project i am not inclined to invest the effort.

Please use `Shift-PgUp` and `Shift-PgDn` keys to move up and down the terminal. Scrolling works in the mobile terminal.

If you are really interested, please raise a PR.
