### ISSUE TITLE
time limit search option -t not able to specify duration

### ISSUE THREAD

**Issue by timeislove** [jarun/ddgr#103]
hello, used both googler and ddgr.

any definiton for SPAN? could you provide more examples of using -t options?

tried -t d3 (like googler), -t 0,3,0 (wild guess), all did not work, though -t d, -t m, -t y work (at least to give out search result but not knowing the time limit period)

the point is how to specify the time limit period?

tkyou very much!!!

**Comment by jarun** [comment]
Do you see it working in the html version? https://duckduckgo.com/html/

**Comment by timeislove** [comment]
> Do you see it working in the html version? https://duckduckgo.com/html/

for the time limit search, could you advise the syntax?

**Comment by jarun** [comment]
Edit in address bar and refresh. I don't see it working so wanted to confirm. We can add year though.

**Comment by timeislove** [comment]
not available in the link (html) you provided nor the common link duckduckgo.com

but possible to select the time range in the search result page.

e.g.

https://duckduckgo.com/?q=delta+airlines&ia=web

**Comment by jarun** [comment]
and it only has day, week, month and year.

**Comment by jarun** [comment]
Year support added at commit efffb62e79caeb0591bb8433a01f895fdbffeb40. That's all we can do here.
