### ISSUE TITLE
bang search not able to show the search results in text mode (cmd line)?

### ISSUE THREAD

**Issue by timeislove** [jarun/ddgr#104]
hello, 

ddgr obama --> text search results in cmdline

ddgr \!w obama --> trigger my firefox to display (for the moment, firefox only be triggered when i select the search index)

any possibility to show the result in cmd line or override the default setting to go to gui browser?

**Comment by jarun** [comment]
This is not available as the program cannot parse all web pages. You can always BROWSER=w3m.
