### ISSUE TITLE
add an option to have longer abstract

### ISSUE THREAD

**Issue by timeislove** [jarun/ddgr#106]
the beauty of text mode search is speed.

if possible to have longer abstract, it may get the info that the user is looking for hence save the time not to start the browser to open the links.

possible to have option to select how many lines of abstract to be displayed?

**Comment by jarun** [comment]
The abstract fetched in html is determined by the server, so no way to optimize that. There wouldn't be much difference between processing the abstract and rendering fewer lines vs. printing what is received from the server.
