### ISSUE TITLE
Change AUR version to 1.8.1

### ISSUE THREAD

**Issue by GoDzM4TT3O** [jarun/ddgr#111]
Hello there!

First of all, thank you for this project! I like it a lot!

Now, what I did was I created a newer package on the AUR, which can be found [here](https://aur.archlinux.org/packages/ddgr-git/). The current version is version 1.8.1, the same as the release version in your repository.

Please update the AUR packaging status (which is [here](https://github.com/jarun/ddgr#from-a-package-manager)) from 1.7 to 1.8.1 :)

**Comment by jarun** [comment]
It's auto-pulled from repology. I can't do much here. You can request the original maintainer to add you as a co-maintainer.

**Comment by jarun** [comment]
I sent a mail to the current maintainer. That's the best I can do right now from my side.

**Comment by GoDzM4TT3O** [comment]
Ok, thank you.

**Comment by jarun** [comment]
AUR is updated.
