### ISSUE TITLE
Option to show just as many results as fit to the terminal window size

### ISSUE THREAD

**Issue by silviubogan** [jarun/ddgr#114]
`ddgr` is wonderful! :+1: 

A small wish of mine is to be able to show just as many results as fit to the terminal window size.

Live adapting to window resize would be a great bonus.

Thank you!

**Comment by jarun** [comment]
> A small wish of mine is to be able to show just as many results as fit to the terminal window size.

Please use the `-n` option. It may be a small wish but it's a lot of work to get the terminal size and print the number of characters exactly etc. Also consider `ddgr` to be a tiny text-based utility to fetch a specified number of results and show them... nothing more than than. I can't spend time maintaining it and as you'll see there are already open issues no one cares to work on.
