### ISSUE TITLE
[Q] Are there any API limits?

### ISSUE THREAD

**Issue by NightMachinary** [jarun/ddgr#122]
Will there be problems if I use this for automatic scraping?

**Comment by jarun** [comment]
This utility is not intended for automatic scraping.

I believe it is an abuse of a free service. If you do that soon DDG may take countermeasures so people who were using it for occasional searches would also lose it.

I am not going to spend too much of my personal time to fix those as I don't use ddgr a lot myself. You can refer to issue #115 for an insight on what happened last time it was broken.
