### ISSUE TITLE
Using ddgr on Windows susbsystem for linux (WSL) seems to not working well. "No results." searchs

### ISSUE THREAD

**Issue by Gurren-Joestar** [jarun/ddgr#123]
Hi, im having some trouble using ddgr in **Ubuntu 20,04.1 (windows subsystem for linux)**, when i use ddgr like this:

`ddgr wikipedia`

I got **this:**

**`No results.`**

![ddgr](https://user-images.githubusercontent.com/71229258/99880370-f2234b00-2be0-11eb-99bc-5325e77709af.png)

I installed ddgr and complements with:

```
sudo apt-get install ddgr
sudo apt-get install elinks
sudo apt-get install lynx
sudo apt-get install python3 python3-requests
```

I even clone the code from github and installed it, but it said i already had it.  

My python3 version is 3.8.3 and i also have miniconda 3 with the same python version

**Comment by jarun** [comment]
Do you think i would help to mention the program version you are using?

Anyway, try the latest release or master.

**Comment by jarun** [comment]
The Ubuntu 20.04 default ddgr version (v1.7 looks like) is dated. Please install manually or using PyPi.

**Comment by Gurren-Joestar** [comment]
Sorry, i forgot to mention the version 
![version](https://user-images.githubusercontent.com/71229258/99880884-25b3a480-2be4-11eb-8915-c7ea1533adfe.png)

`ddgr/focal,now 1.7+git20190928.bccdc92-2 all [installed]
`
What do you think i forgot?

**Comment by jarun** [comment]
Yes, that one is broken. Use v1.9.

**Comment by Gurren-Joestar** [comment]
Thank you, 1.9 works ! 
I wonder why ubuntu looks for 1.7 , I guess it doesnt matter

```
~$ cd ddgr
~/ddgr$ sudo make install
install -m755 -d /usr/local/bin
install -m755 -d /usr/local/share/man/man1
install -m755 -d /usr/local/share/doc/ddgr
gzip -c ddgr.1 > ddgr.1.gz
install -m755 ddgr /usr/local/bin
install -m644 ddgr.1.gz /usr/local/share/man/man1
install -m644 README.md /usr/local/share/doc/ddgr
rm -f ddgr.1.gz
:~/ddgr$ ddgr
ddgr (? for help) wikipedia

 1.  Wikipedia [www.wikipedia.org]
     Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the
     Wikimedia Foundation.

 2.  ‎Wikipedia on the App Store [apps.apple.com]
     Download Wikipedia and enjoy it on your iPhone, iPad, and iPod touch. ‎Explore your world, find a quick fact, or
     dive down a Wikipedia rabbit hole with the official Wikipedia app for iOS. With more than 40 million articles
     across nearly 300 languages, your favorite free online encyclopedia is at your fingertips.

 3.  Wikipedia - Wikipedia [en.wikipedia.org]
     Wikipedia (/ ˌ w ɪ k ɪ ˈ p iː d i ə / wik-ih-PEE-dee-ə or / ˌ w ɪ k i-/ wik-ee-) is a multilingual open-
     collaborative online encyclopedia created and maintained by a community of volunteer editors using a wiki-based
     editing system.It is one of the 15 most popular websites as ranked by Alexa, as of August 2020. Featuring no ads,
     it is hosted by the Wikimedia Foundation, an American non ...
```

**Comment by jarun** [comment]
> I wonder why ubuntu looks for 1.7 , I guess it doesnt matter

It's a big question.
You have to get acquainted to Ubuntu release strategy and post-release update strategy, i am not familiar with those either.
