### ISSUE TITLE
Seeing more than 25 results

### ISSUE THREAD

**Issue by AndreaRe9** [jarun/ddgr#125]
Hi @jarun,
I am conducting a study about page ranking algorithms and, to test and experiment with the results, I need a discrete amount of them for a given query. I was trying to build a little dataset to work with. Is there a way to show more than N=25 results from a web search? Also, is there a straightforward way to show only the results URLs?

Thank you for you answer.

**Comment by jarun** [comment]
As the program help shows, there is no way to do that in the current implementation. There is no way to show only the URLs either. The program is quite generic.

However, both of these are small exercises you can try out easily.
