### ISSUE TITLE
Add option to show results in reverse order

### ISSUE THREAD

**Issue by mrn** [jarun/ddgr#129]
Sometimes the terminal window is too small to display all results, so if the number of results is too large, only the last few results are shown. You have to scroll far to get to the first result.

![image](https://user-images.githubusercontent.com/10130438/124972904-2d1ca680-e02b-11eb-9daa-e9e98b7e38c0.png)

This can be avoided by limiting the number of results, but that's inconvenient when, e.g., binding ddgr to a keyboard shortcut (open a new terminal and run ddgr with a limit) because the new terminal might have any size.

![image](https://user-images.githubusercontent.com/10130438/124972577-d911c200-e02a-11eb-963b-abb0d78488fd.png)

It would be convenient to set ddgr to always show results in reverse, you can scroll up if needed.

**Comment by jarun** [comment]
Sorry, I don't have any bandwidth to do cosmetic changes.
The default order is the same as what's shown in the web.
