### ISSUE TITLE
request for a new release

### ISSUE THREAD

**Issue by chenrui333** [jarun/ddgr#137]
It looks like it has been more than a year since last release, any thoughts on making a new one? Thanks!

**Comment by jarun** [comment]
Yes, we can. I will tr to make it in one of the coming weekends.

**Comment by jarun** [comment]
ddgr v2.0 is released - https://github.com/jarun/ddgr/releases/tag/v2.0

**Comment by chenrui333** [comment]
Thanks @jarun!

**Comment by jarun** [comment]
My pleasure! If you don't mind, please consider sponsoring my work.
I badly need a new rig. So requesting long term users to sponsor. Thanks!
