### ISSUE TITLE
ddgr doesn´t work anymore

### ISSUE THREAD

**Issue by Rosika2** [jarun/ddgr#147]
Hi all, 

info:
my system: Linux/Lubuntu 20.04.5 LTS

I use `ddgr` as a **standalone binary** and it worked well in the past but suddenly it doesn´t seem to work anymore.

I can´t tell exactly  when I used it last ( perhaps 2 weeks ago) but back then it worked.

I **assume** it has something to do with the latest kernel but I can´t be definite about that of course.
The latest kernel on my system is:   linux-generic:amd64 5.4.0.126.127 and I installed it on 2022-09-20.
So I guess the last time I used ddgr was before that date.
 
 ddgr started normally at first:  
` 	ddgr (? for help) `
 However: when I entered a search term (e.g. "bbc") it just said: 
 

```
[ERROR] HTTP Error 403: Forbidden
	No results.
```

	
As far as **dependencies** are concerned I may say on system it should work:
	
	
```
python3 --version
	Python 3.8.10
```

	
Any ideas what might be wrong all of a sudden?

Thanks a lot in advance
Many greetings 
Rosika

**Comment by Rosika2** [comment]
Hi,

sorry. I only now found out that this topic  has already been discussed here.

At least this way I can confirm that the workaround worked well for me.
In the file "ddgr" I changed the user agent in line 88 to 

`USER_AGENT = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0'`

and `ddgr` thus works fine again.

Thanks and many greetings
Rosika  :-)

**Comment by jarun** [comment]
Thanks!
