### ISSUE TITLE
Prompt should always be visible

### ISSUE THREAD

**Issue by user451421541757324** [jarun/ddgr#150]
In the **absence of sufficient vertical space to display all results**, the user is forced to scroll up to read the first result but the prompt disappears. Instead, it would be nice if it was always visible (therefore in a fixed position).

To this, I would add that it would be nice if in the same situation, the user is faced with the upper part of the results (1, 2, 3, ...) and not the lower part (10, 9, 8, ...).

**Comment by chrysle** [comment]
> To this, I would add that it would be nice if in the same situation, the user is faced with the upper part of the results (1, 2, 3, ...) and not the lower part (10, 9, 8, ...).

There is the option `--reverse` which reverses the order of the results.

**Comment by user451421541757324** [comment]
> There is the option `--reverse` which reverses the order of the results.

Thank you, this helps a lot.

I'll leave the issue open, maybe the maintainer is still interested in the "fixed" prompt thing.

**Comment by jarun** [comment]
Please use the `-n N, --num N` option to set the number of results per page depending on your terminal size.
