### ISSUE TITLE
display longer abstract?

### ISSUE THREAD

**Issue by sblazie** [jarun/ddgr#151]
This tool is outstanding. I would love it more if I could view longer abstracts for search results (in json format using --json). It appears to enforce a character limit. Is there a simple way I can increase that limit, such that results will display an abstract of several sentences?
Thanks in advance!

**Comment by jarun** [comment]
I wrote the code years back. Since this is not actually a defect, I can't spend my free time on it anymore. It's easy to trace the code. Search for the string "abstract" and add some prints to see if it is being truncated anywhere. Thanks!
