### ISSUE TITLE
ddgr never returns results

### ISSUE THREAD

**Issue by alinanorakari** [jarun/ddgr#154]
Hello,

no matter which keywords I use, ddgr's response is always `No results.`. Debug mode shows the correct query parameter, however the response body written to `/tmp` only contains the html for the front page with its search form and no results page.

```
─ ddgr -d nike
[DEBUG] ddgr version 1.6 Python version 3.7.3
[DEBUG] q:nike, region:us-en, page:0, curindex:1, safe:1
[DEBUG] nextParams:
[DEBUG] proxy:{'https': None}
[DEBUG] ua:ddgr/1.6 (textmode; Linux x86_64; 1024x768)
[DEBUG] Response body written to '/tmp/ddgr-response-bln9ycs6'.
[DEBUG] Prev nextParams: 
[DEBUG] Next nextParams: 
No results.
ddgr (? for help) q
─ wc -l /tmp/ddgr-response-bln9ycs6 
53 /tmp/ddgr-response-bln9ycs6
─ 
```

**Comment by alinanorakari** [comment]
this is the version packaged for Raspbian

**Comment by jarun** [comment]
Please try master.

**Comment by jarun** [comment]
I don't see any issue with master.
Closing since there is no response for a long time.
