### ISSUE TITLE
[ERROR] HTTP Error 202: Accepted

### ISSUE THREAD

**Issue by pj-connect** [jarun/ddgr#159]
ddgr --np linux bash cheatsheet

[ERROR] HTTP Error 202: Accepted
No results.

This result seems to be random. Other times, I get some results from ddg

**Comment by rwinner** [comment]
This has been fixed in newest version.

Lee 😎

**Comment by pj-connect** [comment]
I have version 2.1, so, sems to be the latest !

**Comment by xanderlewis** [comment]
I've just installed 2.1 too, and have got exactly the same error.

**Comment by rwinner** [comment]
On Thu, Dec 14, 2023 at 12:00:19PM -0800, pj-connect wrote:
> I have version 2.1, so, sems to be the latest !
> 
> -- 

Working here.

-- 
Lee

**Comment by auntchilada** [comment]
me too

$ ddgr -v

2.1

$ ddgr xanadu

[ERROR] HTTP Error 202: Accepted
No results.

**Comment by rwinner** [comment]
On Fri, Dec 15, 2023 at 11:55:07AM -0800, bruno kirby wrote:
> me too
> 
> $ ddgr -v
> 
> 2.1
> 
> $ ddgr xanadu
> 
> [ERROR] HTTP Error 202: Accepted
> No results.

I'm not sure the ver no. has been updated. Just dl the latest version which
includes the fix.

-- 
Lee

**Comment by chrisgrieser** [comment]
I also got that error. I am also on 2.1. 

---

> I'm not sure the ver no. has been updated. Just dl the latest version which
includes the fix.

Don't think there is a version issue, since the 2.1 release was October 2022?

**Comment by jarun** [comment]
Fixed in ddgr 2.2.

**Comment by jarun** [comment]
Works fine at my end.
