### ISSUE TITLE
Screen flickering when using tuir

### ISSUE THREAD

**Issue by levkush** [jarun/ddgr#164]
Hi, I noticed a problem that occurs when i try to implement opening reddit.com urls in tuir.
When I open up a reddit link my screens starts to flicker but this doesn't happen if I use googler instead.

I am using WSL.
ddgr version is 2.2

Here is my implementation:
```
# check_url_script    
                                              
#!/bin/bash

check_url() {
    if [[ "$1" == *"reddit.com/r/"*"/" ]]; then
        subreddit=$(echo "$1" | sed 's/.*reddit.com\/r\/\([^/]*\)\/.*/\1/')
        tuir -s "$subreddit"
    elif [[ "$1" == *"reddit.com/" || "$1" == *"reddit.com" ]]; then
        tuir
    elif [[ "$1" == *"reddit.com"* ]]; then
        tuir "$1"
    else
        elinks "$1"
    fi
}

check_url "$1"
```

And what command I use to start it:
`ddgr --url-handler /home/levkush/check_url_script (search_term)`

**Comment by jarun** [comment]
I tried to repro on master but not seeing the problem. Looks like a local issue, Please debug yourself.

**Comment by jarun** [comment]
In any case, ddgr just invokes the url handler, how it is displayed is not managed by ddgr.
