### ISSUE TITLE
Link result text should wrapped inside small terminal

### ISSUE THREAD

**Issue by ahloiscreamo** [jarun/ddgr#168]
Hello,

currently on ddgr, when i search for something the link result did not wrapped however descriptive content shown for results wrapped out nicely, this is on small terminal window, picture ddg web vs ddgr for comparison 

![Screenshot from 2024-08-25 12-30-35](https://github.com/user-attachments/assets/c32da7fc-52c0-494d-b155-590949f80630)
![Screenshot from 2024-08-25 12-31-14](https://github.com/user-attachments/assets/c0e03524-c7e2-4c57-a8ed-691d3cc7d58b)

**Comment by jarun** [comment]
Sorry, no plans to fix these minor problems anymore. If you have the time, please raise a PR.
The change should be in _print_title_and_url().
