### ISSUE TITLE
Void linux package

### ISSUE THREAD

**Issue by cr6git** [jarun/ddgr#18]
Hi ! 

I created a package for Void linux, see [commit](https://github.com/voidlinux/void-packages/commit/0e43ec82913465509d016f204e3f9ad296695a63). 
To install it: 
`xbps-install ddgr`

Regards.

**Comment by jarun** [comment]
Thanks a lot!!!

You may also want to add googler, imgp, nnn, bcal and pdd.

**Comment by jarun** [comment]
Linked at b2b8a6ff8cd132792b7c620334569dad4608ff91.
