### ISSUE TITLE
somebody please add this to brew for macOS

### ISSUE THREAD

**Issue by chovy** [jarun/ddgr#23]
https://discourse.brew.sh/t/request-ddgr-added-to-brew/1332?u=chovy

**Comment by jarun** [comment]
Thanks for adding the request. @zmwangx I guess we need 50 votes for a package to be accepted?

**Comment by chovy** [comment]
50? c'mon man.

**Comment by jarun** [comment]
I forgot what was the criteria. Can you please share if you know?

**Comment by zmwangx** [comment]
> 50

Yes.

**Comment by chovy** [comment]
Oh I see. Brew won't add it unless it has 50 upvotes? They've become strict in their old age.

**Comment by zmwangx** [comment]
50 stars is nothing on GitHub. And we have actually relaxed the acceptability criteria over time — well, at least over the past few years (I'm speaking from the experience of an ex-Homebrew maintainer and someone who has followed the development for about four years).

**Comment by jarun** [comment]
We'll get there.

**Comment by jarun** [comment]
We have 50+ votes now!

**Comment by zmwangx** [comment]
Cool, I'll add it today.

**Comment by jarun** [comment]
Thank you so much! :)

**Comment by zmwangx** [comment]
One question: why are the "binary" archives marked as x86_64/amd64? I would assume they're all universal, right? I'm not sure about rpm-based systems, but architecture independent debs should be marked as all, think http://ftp.debian.org/debian/pool/main/g/git/git-doc_2.11.0-3+deb9u2_all.deb. Probably something that could be configured with packagecore?

This applies to googler too, I didn't notice it until just now.

**Comment by zmwangx** [comment]
(This is unrelated to Homebrew packaging.)

**Comment by jarun** [comment]
RP guys are hackers. Would stop at nothing. ;)

**Comment by jarun** [comment]
gitter? ;) I wanted to ask something.

**Comment by zmwangx** [comment]
Wait, you're using requests but didn't mention anywhere in README.

**Comment by jarun** [comment]
It's now added in the README and packagecore.yaml.

**Comment by kshitij10496** [comment]
What about creating a PyPI package so that we do not have to maintain separate system-based installers?

**Comment by jarun** [comment]
Frankly, I don't think pip3 is a very reliable way to install stuff. I am already facing issues related to deps version conflicts in 2 of my utilities. We are good with what we have. Also, ddgr can run standalone if you have requests installed. Given the number of deps I don't think we need this.

**Comment by jarun** [comment]
BTW, is it important to let the world know u were born on 10 Apr 1996 ;)? At least use hex!

**Comment by jarun** [comment]
@zmwangx any update on this?

**Comment by zmwangx** [comment]
@jarun Sorry, I stopped when I noticed the undocumented requests dependency and later forgot about it. I've submitted https://github.com/Homebrew/homebrew-core/pull/21370.

However, I'm not quite convinced about the requests dependency. It's quite trivial to replace the two `requests.post` calls with native `urllib.request`, and the code would still be straightforward; I can even send you a patch. That would help get rid of [all these lines](https://github.com/zmwangx/homebrew-core/blob/8880de373b4c398a231244e9bb6d58b69ae8fa6c/Formula/ddgr.rb#L11-L39) that I'll need to update semi-manually each time.

If you insist on the requests dependency though, I'd say you probably want to actually take advantage of it by using a [session](http://docs.python-requests.org/en/master/user/advanced/#session-objects).

**Comment by jarun** [comment]
> I can even send you a patch

Please raise a PR. I was thinking if we need to handle proxies differently...

**Comment by zmwangx** [comment]
I'll hold this off until a requests-less release.

**Comment by jarun** [comment]
Please allow me a day or two...

**Comment by zmwangx** [comment]
No rush. Those who are desperate can simply grab the file from Homebrew/homebrew-core#21370.

**Comment by jarun** [comment]
@zmwangx [ddgr v1.2](https://github.com/jarun/ddgr/releases/tag/v1.2) is released.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/ddgr/commit/580f267f2c193d1ab2f8317f853a8b257d6185b5. Thanks @zmwangx!
