### ISSUE TITLE
Add animated gif to GitHub readme showing use

### ISSUE THREAD

**Issue by trivedi** [jarun/ddgr#28]
[ASCII Cinema](https://asciinema.org) for the win

**Comment by jarun** [comment]
Can you please prepare one and raise the PR? I am really running short of time here. :(

**Comment by trivedi** [comment]
Will try to once I get back to my personal laptop. asciinema not saving on this computer for some reason.

**Comment by jarun** [comment]
Sure! Thanks a lot!

**Comment by jarun** [comment]
I am assuming you are still not back to your personal laptop. Please raise the PR when it's ready. I am closing this issue.
