### ISSUE TITLE
Port created for FreeBSD

### ISSUE THREAD

**Issue by slicer69** [jarun/ddgr#29]
A port for ddgr has been submitted to the FreeBSD Ports project. Is this port is accepted it can be added to the installation instructions in the project's README file. The status of the FreeBSD ddgr port can be found here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223976

**Comment by jarun** [comment]
Thank you!

**Comment by slicer69** [comment]
My pleasure. It looks like the port was accepted this morning so starting next week people will be able to install ddgr on FreeBSD by running either "pkg install ddgr" or "cd /usr/ports/www/ddgr && make install".
