### ISSUE TITLE
Support navigation

### ISSUE THREAD

**Issue by jorgesumle** [jarun/ddgr#3]
Any idea to implement this feature? Looking at the source code of the Next button (https://duckduckgo.com/html/?q=asd) it may seem trivial to build a URL for the next and previous pages:

```
<form action="/html/" method="post">
          <input type="submit" class='btn btn--alt' value="Next" />
          <input type="hidden" name="q" value="asd" />
          <input type="hidden" name="s" value="30" />
          <input type="hidden" name="nextParams" value="Keywords=asd&amp;xargs=12KPjg1pZSrp68i%2D%5FoMPCRErjGnQNVmZ615JIuTcQ%5FQZAD6A5dYdR%5FePqBypItDrUtu0KJk6nQo%5FpPIfD7ucu6&amp;hData=12KPjg1qdOxJy7tuqnF9W2TOSj8m4%2E" />
          <input type="hidden" name="v" value="l" />
          <input type="hidden" name="o" value="json" />
          <input type="hidden" name="dc" value="31" />
          <input type="hidden" name="api" value="/d.js"/>
          <input name="kl" value="us-en" type="hidden" />
</form>
```

But https://duckduckgo.com/html/?q=sample&s=30&dc=31 just shows a website with the following message: 

> If this error persists, please let us know: ops@duckduckgo.com

**Comment by jarun** [comment]
It would be great if you can contribute this feature. I believe you need to use a request with form data/payload. If you need examples, look [here](http://stackoverflow.com/questions/10768522/python-send-post-with-header).

**Comment by jorgesumle** [comment]
```
from urllib.parse import urlencode
from urllib.request import Request, urlopen

url = 'https://duckduckgo.com/html'
post_fields = {'q': 'hola', 's': '30', 'nextParams': '', 'v': 'l', 'o': 'json', 'dc': '31', 'api': '/d.js', 'kl': 'us-en'}

request = Request(url, urlencode(post_fields).encode())
json = urlopen(request).read().decode()
print(json)
```
Here is some code to make POST requests to DuckDuckGo. I'm not sure how to make it work as I want though.

**Comment by jarun** [comment]
I'm not sure myself. :) I think the best option would be to get in touch with the ddgr team.

**Comment by jorgesumle** [comment]
I found a simple solution to make pagination work up to result 30: https://notabug.org/Ducker/ducker/commit/91ecc0c2619abd1f2d2ead02a38beef6231d46f2. Obviously this is not a definitive solution. The idea is to keep all results and download 30 more results when result 31 is requested. What do you think?

**Comment by jarun** [comment]
We must keep it dynamic to retain scalability. How many pages would you store?

**Comment by jorgesumle** [comment]
> We must keep it dynamic to retain scalability

Sorry, I don't understand. What do you mean with that?

> How many pages would you store?

1, and if result 31 is requested, 2. It seems that not DuckDuckGo not always displays 30 results, so a page may have less results.

**Comment by jarun** [comment]
How about result 61?

**Comment by jorgesumle** [comment]
Then 3 pages. I don't think that's a good solution though. The update method should probably be changed, as changing the URL has not any effect.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/ddgr/commit/8b527d53a63983910e59b0ffd332228696d21852.
