### ISSUE TITLE
auto-completion scripts aren't installed

### ISSUE THREAD

**Issue by yurivict** [jarun/ddgr#31]
Please install them, but make installation predicated on some build variable so that the user has control.

**Comment by jarun** [comment]
Sorry, this is too specific to individual preferences and supporting these become a headache at some point of time. If you want, please write an unofficial script and share it here. But again, we won't be able to support it.

**Comment by yurivict** [comment]
What preferences? The locations are standard, the installation is controlled by a variable. There's nothing that falls under the preference category.

**Comment by jarun** [comment]
Please refer to:

https://github.com/jarun/googler/pull/88

Officially, the stand is - we don't want to extend support towards (un)installation of completion scripts. They are provided as ad-hoc.
