### ISSUE TITLE
This should be available through pip

### ISSUE THREAD

**Issue by carc1n0gen** [jarun/ddgr#32]

**Comment by jarun** [comment]
@shaggytwodope I leave it to you. Take the call if you _want_to_ and can maintain it.

**Comment by jarun** [comment]
@carc1n0gen personally, I have no fascination for pip. ddgr has a single dependency. In addition, it's not a library someone can re-use.

**Comment by barraponto** [comment]
if it had a setup.py file, it would be possible to install from github directly.

**Comment by jarun** [comment]
@barraponto can you please raise a PR?

**Comment by carc1n0gen** [comment]
@jarun pip isn't just for libraries.  It is very common to install python command line executables with pip (usually in to it's own virtualenv)

**Comment by jarun** [comment]
@carc1n0gen maintaining on every release is the real problem.

**Comment by jarun** [comment]
Sorry, can't have this in without a willing maintainer. If any of you guys is interested, please raise a PR directly.

**Comment by jarun** [comment]
Dependency on requests, urllib3 are gone for good in release v1.2. `ddgr` is now a standalone executable if you have Python3 installed on your distro.
