### ISSUE TITLE
Suggestion: Implement a weather feature for the current user's location

### ISSUE THREAD

**Issue by mazh91** [jarun/ddgr#33]
As a user, I can run `ddgr weather` to see the weather forecast for my current location

- [ ] Weather forecast for the day shows on top of the search results
- [ ] Temperature units are in `°C` or `°F` depending on my location
- [ ] The wiki is updated for the use this feature with an example

**Comment by jarun** [comment]
Sorry, I don't intend to make ddgr a weather checking utility.

You can use the bang feature to look up weather at your place but that's about it.
