### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by kehugter** [jarun/ddgr#36]
> Configuration file
> `ddgr` doesn't have any! Use aliases, environment variables and auto-completion scripts.

https://github.com/jarun/ddgr/blob/fdab414d561e742ffb04585eb8155a64ce565dfb/README.md#configuration-file

Is this decision final? I'd really prefer to set my defaults in a configuration file. Aliases are the closest in terms of ease of maintenance and backup, but at least in fish aliases don't autocomplete.

**Comment by jarun** [comment]
> Is this decision final?

Yes. Keeps things simpler, lesser maintenance.

**Comment by kehugter** [comment]
> Keeps things simpler, lesser maintenance.

For the maintainer, but not necessarily for the user. Thanks anyway.

**Comment by jarun** [comment]
True. Thanks for your understanding.
