### ISSUE TITLE
Method to make a proxy setting persistant?

### ISSUE THREAD

**Issue by subscriptionblocker** [jarun/ddgr#38]
Say I had a proxy at 192.168.2.103:8118. How could I set ddgr up where I would *never* accidentally access the web without going through the proxy? In the past, I always did this through the browser settings - not as a global change to networking.

Any tips appreciated.

**Comment by jarun** [comment]
alias d='ddgr -p 192.168.2.103:8118' and use `d` to run ddgr all the time.
