### ISSUE TITLE
Problem with results: URLs not staring with 'www.' do not offer an open option

### ISSUE THREAD

**Issue by CottonEaster** [jarun/ddgr#39]
I'm using Gnome terminal, on Mint 18.3 Cinnamon. The results list contains URLs, coloured brown. Clicking or double-clicking them does nothing; but that's fair enough, since a context menu offers 'open link', and it works. However, one of my results - I searched for the word 'test' - starts not with 'www.' (which all the others did) but with '.beta', and it offered no 'open link' in the context menu. Is this a limitation of my terminal emulator? Thanks.

**Comment by jarun** [comment]
Here's what you see:

```
~$ d test

 (1) Find online tests, practice test, and test creation software ...  [www.test.com]
Online tests and testing for certification, practice tests, test making tools, medical testing and more.

 (2) Test | Definition of Test by Merriam-Webster  [www.merriam-webster.com]
Define test: a means of testing: such as — test in a sentence

 (3) Speedtest by Ookla - The Global Broadband Speed Test  [beta.speedtest.net]
Test your Internet connection bandwidth to locations around the world with this interactive broadband speed test from Ookla

 (4) Test | Define Test at Dictionary.com  [www.dictionary.com]
Test definition, the means by which the presence, quality, or genuineness of anything is determined; a means of trial. See more.

 (5) Test - definition of test by The Free Dictionary  [www.thefreedictionary.com]
test 1 (tĕst) n. 1. A procedure for critical evaluation; a means of determining the presence, quality, or truth of something; a trial: a test of one's eyesight ...

 (6) Test - Wikipedia  [en.wikipedia.org]
Test, TEST or Tester may refer to: Test (assessment), an assessment intended to measure the respondents' knowledge or other abilities; Medical test, to detect ...

 (7) Speedtest.net by Ookla - Results  [www.speedtest.net]
Test your Internet connection bandwidth to locations around the world with this interactive broadband speed test from Ookla

 (8) Tests: IQ tests, personality tests, love tests, career tests  [www.queendom.com]
Tests & quizzes: free IQ test, Big 5 personality test, emotional intelligence test (EQ), love tests, career aptitudes test, self-esteem self-test, communication ...

 (9) Tests.com Practice Tests  [www.tests.com]
Free practice tests and other test resources organized in 300 categories including: academic, career, personality, intelligence, and more.

 (10) Speakeasy Internet Speed Test - Check Your Broadband Speed ...  [www.speakeasy.net]
The internet speed test trusted by millions. Use our free bandwidth test to check your speed and get the most from your ISP. New HTML5 speed test, no Flash.

ddgr (? for help)
```

In the 3<sup>rd</sup> result there is no sub-domain `www` which is [absolutely fine](https://serverfault.com/questions/145777/what-s-the-point-in-having-www-in-a-url) spec-wise.

If what you need are full URLs, please use the `-x` option or omniprompt key `x` to toggle when the program is running.

**Comment by jarun** [comment]
It's not a limitation of your terminal either. It can't decide whether `abc.def` is a valid url or typo without a DNS lookup which you don't want it to be doing for privacy reasons. Also, the solution will be stronger than the problem.

**Comment by CottonEaster** [comment]
OK, thanks. Sadly, I don't fully understand what you say about DNS. Might you be good enough to explain the risk here? Also, is there still a risk if one uses a VPN? Thank you for your time.

**Comment by jarun** [comment]
I just told a possibility. Terminals don't work that way so forget about it. Use the expanded mode.
