### ISSUE TITLE
[macOS] Prompt escape sequences error

### ISSUE THREAD

**Issue by paxperscientiam** [jarun/ddgr#40]
Hey there @jarun , great project!

Small bug i've noticed is that, after conducting a search, the ddgr prompt is a bit funny due to possible syntax error.

On my machine I get this literal string for the prompt: `[7mddgr (? for help)[0m`

The code, should be something like this: `'\e[7mddgr (? for help)\e[0m`

````bash
$ echo -e '\e[7mddgr (? for help)\e[0m'
=> ddgr (? for help)
````

**Comment by jarun** [comment]
> On my machine

Details please? OS, terminal, locale?

It's as per the color coding guidelines already so I am expecting your terminal has something in play here.

**Comment by paxperscientiam** [comment]
Hey,

Terminal: iTerm2

OS: macOS 10.13.2


shell environment variables
````
TERM=xterm-256color
````

and `locale` gives...
````
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
````


Does that help?


On Sun, Dec 10, 2017 at 9:51 PM, Arun Prakash Jana <notifications@github.com

**Comment by jarun** [comment]
I believe this is the same as https://github.com/jarun/googler/issues/203. We had a patch in and then we had to revert it back due to glaring side-effects. At this point we don't have any other way to handle it. One way would be to disable readline but that would be telling on user experience.

**Comment by jarun** [comment]
What do you see if you run the following python3 snippet?

```
#!/usr/bin/env python3
import readline

message = 'ddgr (? for help)'
prompt = '\x1b[7m' + message + '\x1b[0m' + ' '
try:
    cmd = input(prompt)
except EOFError:
    sys.exit(0)
```

**Comment by jarun** [comment]
Given this is the second time this issue is reported, I am working on a way to handle this. I will add the support for an environment variable, which, if defined, will render a plain prompt. Even if the issue is not widespread, it can put-off several users... so it's better to have a way to _avoid_ it.

**Comment by paxperscientiam** [comment]
Hey @jarun , I know I meant to response ... but obviously I forgot!

Running your snippet with python3 yield this:
```python
7mddgr (? for help)[0m
```

**Comment by jarun** [comment]
We have introduced a new env var to disable the prompt color:

    export DISABLE_PROMPT_COLOR=1
It should work in all cases whatever the readline version is.

**Comment by paxperscientiam** [comment]
With that said, one could set an alias like this:
`alias ddgr='DISABLE_PROMPT_COLOR=1 ddgr'`
