### ISSUE TITLE
Allow download files

### ISSUE THREAD

**Issue by kenorb** [jarun/ddgr#43]
I'd like to search for some files and download them, e.g. using the following query:

    site:duckduckgo.com filetype:pdf

I've created similar tool [`google_dl`](https://github.com/mycognitive/google_dl), where I can run:

    google_dl -s duckduckgo.com -f pdf ""

and it'll download all PDF files.

Can a similar feature be implemented in this tool?

**Comment by jarun** [comment]
Sorry, `ddgr` is just the interface to the search results. We will not support scripted auto-downloading.

**Comment by jarun** [comment]
Please note that you can easily extend ddgr to get the pdf files links and download them. As for the current project, I would leave out maintaining extra functionality like these.
