### ISSUE TITLE
pip install support

### ISSUE THREAD

**Issue by timotk** [jarun/ddgr#50]
Hi,

Is it possible to make `ddgr` installable via pip?

Thanks!

**Comment by jarun** [comment]
It's a single file sans any dependencies other than core Python3. Why do you want to add pip to the mix?

**Comment by timotk** [comment]
I think it provides an easy way to install the program. It eliminates cloning the repository and it's independent of system repositories. I also believe it shouldn't be that difficult. I think it's just registering and uploading to PyPi. Do you agree?
