### ISSUE TITLE
Not found by apt

### ISSUE THREAD

**Issue by TomasHubelbauer** [jarun/ddgr#51]
Hey, neither `googler` nor `ddgr` are found for me when doing `apt install`. Do I need to add new sources or something first? If so, can you mention the complete installation steps in the README?

**Comment by jarun** [comment]
I think you to enable the universe/multiverse source and run apt upgrade.

**Comment by jarun** [comment]
Both are in the Miscellaneous section: https://packages.ubuntu.com/bionic/misc/

You'll have to enable it. I will mention it in the README.

**Comment by jarun** [comment]
Misc is enabled by default. It's sufficient to run:

    apt-get upgrade
    apt-get install ddgr

**Comment by TomasHubelbauer** [comment]
Let me update this issue, then. I am doing this in WSL (Windows Subsystem for Linux) and upon doing what you mention, I still get `E: Unable to locate package ddgr`. I am not sure if you care about WSL support, but I think it's good to have a tracking issue for this.

**Comment by jarun** [comment]
WSL is based on 16.04. ddgr is not available on it.
