### ISSUE TITLE
debian install (1.4): [ERROR] <urlopen error no host given>

### ISSUE THREAD

**Issue by smeagolthellama** [jarun/ddgr#54]
I installed this from the Debian repo (testing), but when I tried it, it output
```
[ERROR] <urlopen error no host given>
No results.
```

**Comment by jarun** [comment]
@szlin can you please check this issue?

**Comment by jarun** [comment]
@smeagolthellama can you please share the exact steps? What did you exactly try?

**Comment by szlin** [comment]
@jarun of course.
@smeagolthellama  could you provide the steps for reproducing?

**Comment by smeagolthellama** [comment]
what I did:

1. install using apt-get
2. `ddgr hello world`

and that's it.

According to apt, I have version 1.4-1.

**Comment by smeagolthellama** [comment]
when I use -d, the output is the following:
```
[DEBUG] ddgr version 1.4
[DEBUG] Python version 3.6.5
[DEBUG] q:hello world, region:us-en, page:0, curindex:1, safe:1
[DEBUG] nextParams:
[DEBUG] proxy:{'https': 'http://'}
[ERROR] <urlopen error no host given>
No results.
```

**Comment by szlin** [comment]
Please see the result in my site without any error, does the machine network function work?

szlin@szlin:~$ ddgr --version
1.4
szlin@szlin:~$ ddgr hello world

 (1) HelloWorld, A Merkle Company  [www.helloworld.com]
A powerful combination of native technology and marketing strategy allowing brands to create unforgettable interactions, drive consumer demand
and accelerate growth.

 (2) "Hello, World!" program - Wikipedia  [en.wikipedia.org]
A "Hello, World!"program is a computer program that outputs or displays "Hello, World!" to a user. Being a very simple program in most
programming languages, it is often used to illustrate the basic syntax of a programming language for a working program.

**Comment by jarun** [comment]
@smeagolthellama you have a broken proxy.

Either `https_proxy` OR `HTTPS_PROXY` is set to `http://` in your environment. Fix it and everything should work properly.

**Comment by szlin** [comment]
@smeagolthellama I just let my machine up-to-date and still got no issue on it. 
It might be a network issue just like @jarun mentioned, please have a look.

**Comment by smeagolthellama** [comment]
@jarun Ah. yes. that's it. Both in fact. (Any way to fix that, by the way?)

**Comment by smeagolthellama** [comment]
works now.
