### ISSUE TITLE
Disable colors by default, when piping

### ISSUE THREAD

**Issue by kenorb** [jarun/ddgr#57]
```
$ ddgr -x --np example | cat -v | head
^[[96m (1)^[[0m ^[[32;1mExample | Definition of Example by Merriam-Webster^[[0m
^[[33mhttps://www.merriam-webster.com/dictionary/example^[[0m
$ ddgr --version
1.4
```

I'm aware of `-C`, but I think disabling colors on non-interactive terminal usually is the default behaviour of many utils such as `grep`, `rg`, etc.

**Comment by jarun** [comment]
We can't default to `-C` and change the current behaviour, Please use `-C`.
