### ISSUE TITLE
'site' related query ignored

### ISSUE THREAD

**Issue by kenorb** [jarun/ddgr#58]
For example, when I run:

    ddgr -x "site:https://www.youtube.com/watch"

I get different results than I run the same query on the [website](https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fwww.youtube.com%2Fwatch). For example I get like gdata.youtube.com, or help.youtube.com.

It works when using `googler`.

What am I missing?

**Comment by jarun** [comment]
> What am I missing?

You missed the entire help section. Generally there's one with every utility. For example, ddgr has option `-w` for site-specific search.
