### ISSUE TITLE
Does ddgr need to open a proxy?

### ISSUE THREAD

**Issue by grayFinger** [jarun/ddgr#60]
My first search suggests: 
[ERROR] HTTPSConnectionPool(host='duckduckgo.com', port=443): Max retries exceeded with url: /html (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa26d8fbda0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
No results.

**Comment by jarun** [comment]
> Does ddgr need to open a proxy?

No.

In which country are you?
Did you use any other parameters?
Do you need to use a proxy to connect to the internet?
Are you behind a firewall?

**Comment by jarun** [comment]
Also, can you check if `googler` works fine for you?

**Comment by jarun** [comment]
Closing this as no response is received.
