### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED every query

### ISSUE THREAD

**Issue by ReagentX** [jarun/ddgr#66]
After installing from `brew` every query returns the following:

    [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

**Comment by ReagentX** [comment]
Fixed by running `/Applications/Python 3.7/Install Certificates.command`.

**Comment by idkjs** [comment]
Thanks @ReagentX. More explanation here https://stackoverflow.com/a/42098127/2336356
