### ISSUE TITLE
Missing results in site-specific search

### ISSUE THREAD

**Issue by dcabo** [jarun/ddgr#75]
I've been using `ddgr` for a while without issues, but today found something unusual. After a while looking into it, I can't explain the discrepancies: this site-specific query returns no results:

```
neko:~ $ ddgr --debug --nop -w elecciones.mir.es presidente
[DEBUG] ddgr version 1.5
[DEBUG] Python version 3.6.3
[DEBUG] q:presidente site:elecciones.mir.es, region:us-en, page:0, curindex:1, safe:1
[DEBUG] nextParams:
[DEBUG] proxy:{'https': None}
[DEBUG] Response body written to '/var/folders/vv/3b_s7ws91k1gr7bthlsl4b800000gn/T/ddgr-response-hxnqucjy'.
[DEBUG] Prev nextParams: 
[DEBUG] Next nextParams: 
No results.
```

But the same query returns plenty of them [online](https://duckduckgo.com/?q=site%3Aelecciones.mir.es+presidente&ia=web).

I wondered whether I was being blacklisted by DuckDuckGo, but other similar queries do return results:

```
neko:~ $ ddgr --debug --nop -w elecciones.mir.es congreso
[DEBUG] ddgr version 1.5
[DEBUG] Python version 3.6.3
[DEBUG] q:congreso site:elecciones.mir.es, region:us-en, page:0, curindex:1, safe:1
[DEBUG] nextParams:
[DEBUG] proxy:{'https': None}
[DEBUG] Response body written to '/var/folders/vv/3b_s7ws91k1gr7bthlsl4b800000gn/T/ddgr-response-y6haijts'.
[DEBUG] Prev nextParams: 
[DEBUG] Next nextParams: 
 (1) Elecciones Generales 2011 - Congreso - Municipios de Sevilla  [elecciones.mir.es]
 ...
```

I reproduced this from a different OS X laptop, from a different IP. Any idea what could be going on? Thanks.

**Comment by jarun** [comment]
`ddgr` uses the non-js version.

Search `site:elecciones.mir.es presidente` at https://duckduckgo.com/html/.

We can't do much here. But you can contact DDG and ask the reason. Do update us if you find some info.

**Comment by dcabo** [comment]
Thanks, that's useful to know! I'll follow up.

**Comment by dcabo** [comment]
Just fyi, I reported this to DuckDuckGo twice but got no response/explanation. The error on their side still persists: no results are shown for certain queries, like the one above, in the HTML or Lite versions. Which I find really weird. 🤷‍♂️
