### ISSUE TITLE
Support search bangs in different positions

### ISSUE THREAD

**Issue by shmerl** [jarun/ddgr#79]
DuckDuckGo supports placing search bangs anywhere in the search string. I always commonly place it **after** the thing I'm searching for. That doesn't work with ddgr.

**Comment by jarun** [comment]
Hi, would it be possible for you to raise a PR?

**Comment by shmerl** [comment]
I'll look into it, if I have time.

**Comment by jarun** [comment]
Is there any problem functionality-wise?

**Comment by shmerl** [comment]
No, just usability.

**Comment by jarun** [comment]
I think we can live without this.
Before typing a search in 99% of the cases one would know which site to search. We will not handle this case.

**Comment by shmerl** [comment]
Actually, you'd rather first type what you are searching for, and only then decide if you want to specialize the search with a bang. That's the common pattern usage for DDG,

**Comment by jarun** [comment]
I know there would be use-cases. I also know there's `^A` that takes your cursor to the beginning.

Also, on a terminal, let's say you want to:

```
ls -l long_file_path
vi long_file_path
```

You have to use `^A`, edit and do. A webbrowser use-case may not be the same as terminal use-case all the time.

Anyway, if you really need it, please raise the PR.
