### ISSUE TITLE
option 'x' should refresh the current page

### ISSUE THREAD

**Issue by Boruch-Baum** [jarun/ddgr#81]
When I'm on a page and want ot toggle url expansion, it's because I want to see the urls for the currently displayed results. Currently, I seem to need to press 'n' and 'p' to refresh the screen. Is there a better way? Could there be an option to refresh the current page, or to make the 'x' option automatically refresh the current page?

**Comment by jarun** [comment]
I think we should make x refresh the current page. Can you kindly raise a PR?

**Comment by Boruch-Baum** [comment]
Unfortunately, unlikely any time soon.
