### ISSUE TITLE
Add Italian?

### ISSUE THREAD

**Issue by xzj8b3** [jarun/ddgr#82]
Add Italian?

So maybe others can use it comfortably too, right?

**Comment by jarun** [comment]
Internationalization is not planned. Are you having any problem with the keys?

**Comment by xzj8b3** [comment]
> Internationalization is not planned. Are you having any problem with the keys?

It's a nice tool, but useless without internationalization ... And it would be nice to create tools thinking that others can easily use it

**Comment by jarun** [comment]
You can run a region specific search using the [URL params](https://duckduckgo.com/params).

For example:

```
$ ddgr -r it-it juventus

     La Juventus Football Club, meglio nota come Juventus, è una società calcistica italiana per azioni
     con sede a Torino.                          More at Wikipedia (IT)

 1.  Home - Juventus.com [www.juventus.com]
     Juventus Football Club S.p.A. Via Druento, 175 10151 Torino - Italia; CONTACT CENTER 899.999.897 dal
     lunedì al venerdì dalle 10 alle 20 e il sabato dalle 10 alle 14.

 2.  Calciomercato Juventus - News Mercato - Notizie Calcio Juventus ... [www.calciomercato.com]
     Juventus: gli ultimi movimenti di calciomercato, le news dagli spogliatoi. Risultati, dirette e
     indiscrezioni di mercato: se tifi Juventus leggi Calciomercato.com.

 3.  News Juventus: Notizie, Calciomercato e Risultati Live - Tuttosport [www.tuttosport.com]
     Segui tutte le news sulla Juventus su Tuttosport: novità in anteprima, interviste, scoop di
     calciomercato e risultati in tempo reale della Vecchia Signora!

 4.  Tutto Juve: Ultime notizie [www.tuttojuve.com]
     La Juventus porta a casa i tre punti con il Frosinone, con la consapevolezza che doveva essere una
     pratica sbrigata...

 5.  Juventus, Paratici: ''Allegri resterà con noi. Icardi? Se ne riparla a ... [www.repubblica.it]
     TORINO - L'interesse estivo per Icardi, anche se "ultimamente non ci sono stati contatti" con Wanda
     Nara, ma anche la lista della spesa sul mercato italiano e il prossimo impegno in Champions League a
     Madrid contro l'Atletico. Fabio Paratici, direttore generale della Juventus ...

 6.  Juventus news, calcio, notizie - Sportmediaset [www.sportmediaset.mediaset.it]
     Juventus: tutte le news, gli approfondimenti, le notizie, i video, i risultati, i protagonisti, le
     esclusive e le interviste della tua squadra del cuore:...

 7.  Juventus News | Calciomercato | Ultime Notizie - Calcionews24 [www.calcionews24.com]
     Juventus News: Tutto quello che c'è da sapere sulla squadra di Torino. Le news sul Calciomercato,
     Interviste, Calendario, Risultati, Formazione e le ultime notizie con aggiornamenti in tempo reale
     della Juventus FC.

 8.  Juventus, un Rambo per la Champions: tutto quello che c'è da sapere su ... [www.tuttosport.com]
     TORINO - Ramsey è uno tosto: in Inghilterra lo chiamano Rambo. Il motivo? A 12 anni fu protagonista
     di una rissa e l'allenatore fu costretto a sostituirlo. Poi nello spogliatoio gli disse: sembravi
     Rambo. Un carattere forte quello del centrocampista che ha firmato con la Juventus e a ...

 9.  Juventus Football Club - Wikipedia [it.wikipedia.org]
     La Juventus Football Club (dal latino: iuventūs, «gioventù»), meglio nota come Juventus
     (/juˈvɛntus/), è una società calcistica italiana con sede nella città di Torino.

 10. Juventus TV [pass.juventus.com]
     Enjoy 12 months of full matches from the UEFA Champions League, Serie A TIM and TIM Cup, behind the
     scenes action, classic moments from the club's past and much, much more.
```

ddgr interface is minimal and as you haven't specified what you are looking for in Italian I can't help much here. The options will remain in English characters. If you are looking for an Italian help, add an Wiki page and I can link it from the main page.

**Comment by xzj8b3** [comment]
> You can run a region specific search using the [URL params](https://duckduckgo.com/params).
> 
> For example:
> 
> ```
> $ ddgr -r it-it juventus
> 
>      La Juventus Football Club, meglio nota come Juventus, è una società calcistica italiana per azioni
>      con sede a Torino.                          More at Wikipedia (IT)
> 
>  1.  Home - Juventus.com [www.juventus.com]
>      Juventus Football Club S.p.A. Via Druento, 175 10151 Torino - Italia; CONTACT CENTER 899.999.897 dal
>      lunedì al venerdì dalle 10 alle 20 e il sabato dalle 10 alle 14.
> 
>  2.  Calciomercato Juventus - News Mercato - Notizie Calcio Juventus ... [www.calciomercato.com]
>      Juventus: gli ultimi movimenti di calciomercato, le news dagli spogliatoi. Risultati, dirette e
>      indiscrezioni di mercato: se tifi Juventus leggi Calciomercato.com.
> 
>  3.  News Juventus: Notizie, Calciomercato e Risultati Live - Tuttosport [www.tuttosport.com]
>      Segui tutte le news sulla Juventus su Tuttosport: novità in anteprima, interviste, scoop di
>      calciomercato e risultati in tempo reale della Vecchia Signora!
> 
>  4.  Tutto Juve: Ultime notizie [www.tuttojuve.com]
>      La Juventus porta a casa i tre punti con il Frosinone, con la consapevolezza che doveva essere una
>      pratica sbrigata...
> 
>  5.  Juventus, Paratici: ''Allegri resterà con noi. Icardi? Se ne riparla a ... [www.repubblica.it]
>      TORINO - L'interesse estivo per Icardi, anche se "ultimamente non ci sono stati contatti" con Wanda
>      Nara, ma anche la lista della spesa sul mercato italiano e il prossimo impegno in Champions League a
>      Madrid contro l'Atletico. Fabio Paratici, direttore generale della Juventus ...
> 
>  6.  Juventus news, calcio, notizie - Sportmediaset [www.sportmediaset.mediaset.it]
>      Juventus: tutte le news, gli approfondimenti, le notizie, i video, i risultati, i protagonisti, le
>      esclusive e le interviste della tua squadra del cuore:...
> 
>  7.  Juventus News | Calciomercato | Ultime Notizie - Calcionews24 [www.calcionews24.com]
>      Juventus News: Tutto quello che c'è da sapere sulla squadra di Torino. Le news sul Calciomercato,
>      Interviste, Calendario, Risultati, Formazione e le ultime notizie con aggiornamenti in tempo reale
>      della Juventus FC.
> 
>  8.  Juventus, un Rambo per la Champions: tutto quello che c'è da sapere su ... [www.tuttosport.com]
>      TORINO - Ramsey è uno tosto: in Inghilterra lo chiamano Rambo. Il motivo? A 12 anni fu protagonista
>      di una rissa e l'allenatore fu costretto a sostituirlo. Poi nello spogliatoio gli disse: sembravi
>      Rambo. Un carattere forte quello del centrocampista che ha firmato con la Juventus e a ...
> 
>  9.  Juventus Football Club - Wikipedia [it.wikipedia.org]
>      La Juventus Football Club (dal latino: iuventūs, «gioventù»), meglio nota come Juventus
>      (/juˈvɛntus/), è una società calcistica italiana con sede nella città di Torino.
> 
>  10. Juventus TV [pass.juventus.com]
>      Enjoy 12 months of full matches from the UEFA Champions League, Serie A TIM and TIM Cup, behind the
>      scenes action, classic moments from the club's past and much, much more.
> ```
> 
> ddgr interface is minimal and as you haven't specified what you are looking for in Italian I can't help much here. The options will remain in English characters. If you are looking for an Italian help, add an Wiki page and I can link it from the main page.

But is there a way to get the results of the research in Italian?

Maybe I didn't understand how to do it. Please explain.

**Comment by jarun** [comment]
The results are in Italian:

```
Juventus Football Club S.p.A. Via Druento, 175 10151 Torino - Italia; CONTACT CENTER 899.999.897 dal lunedì al venerdì dalle 10 alle 20 e il sabato dalle 10 alle 14.
```

You have to use the option `-r it-it` to get results in Italian.

**Comment by xzj8b3** [comment]
> You can run a region specific search using the [URL params](https://duckduckgo.com/params).
> 
> For example:
> 
> ```
> $ ddgr -r it-it juventus
> 
>      La Juventus Football Club, meglio nota come Juventus, è una società calcistica italiana per azioni
>      con sede a Torino.                          More at Wikipedia (IT)
> 
>  1.  Home - Juventus.com [www.juventus.com]
>      Juventus Football Club S.p.A. Via Druento, 175 10151 Torino - Italia; CONTACT CENTER 899.999.897 dal
>      lunedì al venerdì dalle 10 alle 20 e il sabato dalle 10 alle 14.
> 
>  2.  Calciomercato Juventus - News Mercato - Notizie Calcio Juventus ... [www.calciomercato.com]
>      Juventus: gli ultimi movimenti di calciomercato, le news dagli spogliatoi. Risultati, dirette e
>      indiscrezioni di mercato: se tifi Juventus leggi Calciomercato.com.
> 
>  3.  News Juventus: Notizie, Calciomercato e Risultati Live - Tuttosport [www.tuttosport.com]
>      Segui tutte le news sulla Juventus su Tuttosport: novità in anteprima, interviste, scoop di
>      calciomercato e risultati in tempo reale della Vecchia Signora!
> 
>  4.  Tutto Juve: Ultime notizie [www.tuttojuve.com]
>      La Juventus porta a casa i tre punti con il Frosinone, con la consapevolezza che doveva essere una
>      pratica sbrigata...
> 
>  5.  Juventus, Paratici: ''Allegri resterà con noi. Icardi? Se ne riparla a ... [www.repubblica.it]
>      TORINO - L'interesse estivo per Icardi, anche se "ultimamente non ci sono stati contatti" con Wanda
>      Nara, ma anche la lista della spesa sul mercato italiano e il prossimo impegno in Champions League a
>      Madrid contro l'Atletico. Fabio Paratici, direttore generale della Juventus ...
> 
>  6.  Juventus news, calcio, notizie - Sportmediaset [www.sportmediaset.mediaset.it]
>      Juventus: tutte le news, gli approfondimenti, le notizie, i video, i risultati, i protagonisti, le
>      esclusive e le interviste della tua squadra del cuore:...
> 
>  7.  Juventus News | Calciomercato | Ultime Notizie - Calcionews24 [www.calcionews24.com]
>      Juventus News: Tutto quello che c'è da sapere sulla squadra di Torino. Le news sul Calciomercato,
>      Interviste, Calendario, Risultati, Formazione e le ultime notizie con aggiornamenti in tempo reale
>      della Juventus FC.
> 
>  8.  Juventus, un Rambo per la Champions: tutto quello che c'è da sapere su ... [www.tuttosport.com]
>      TORINO - Ramsey è uno tosto: in Inghilterra lo chiamano Rambo. Il motivo? A 12 anni fu protagonista
>      di una rissa e l'allenatore fu costretto a sostituirlo. Poi nello spogliatoio gli disse: sembravi
>      Rambo. Un carattere forte quello del centrocampista che ha firmato con la Juventus e a ...
> 
>  9.  Juventus Football Club - Wikipedia [it.wikipedia.org]
>      La Juventus Football Club (dal latino: iuventūs, «gioventù»), meglio nota come Juventus
>      (/juˈvɛntus/), è una società calcistica italiana con sede nella città di Torino.
> 
>  10. Juventus TV [pass.juventus.com]
>      Enjoy 12 months of full matches from the UEFA Champions League, Serie A TIM and TIM Cup, behind the
>      scenes action, classic moments from the club's past and much, much more.
> ```
> 
> ddgr interface is minimal and as you haven't specified what you are looking for in Italian I can't help much here. The options will remain in English characters. If you are looking for an Italian help, add an Wiki page and I can link it from the main page.

ddgr -r it-it  

but does it support website translation?

It is a wonderful tool, as soon as installed I will study it more thoroughly

If I wanted to add a proxy is it possible?

**Comment by jarun** [comment]
> but does it support website translation?

no

> If I wanted to add a proxy is it possible?

yes

**Comment by xzj8b3** [comment]
Just see proxy and Italian....

Great tool really, I had just installed it and I'm now looking at all the options
I

**Comment by jarun** [comment]
:+1: glad you like it!
