### ISSUE TITLE
ddgr does not return a link to the found item, and instead returns a link to the site.

### ISSUE THREAD

**Issue by drmcnelson** [jarun/ddgr#84]
In searching google scholar,   ddgr returns links to sites such as researchgate.com. etc.   This is because the default is to not expand urls.

The expected behavior is to return a link to the specific item, i.e. the research publication, rather than to the host site.

Therefore, it seems the default should be to expand urls.

**Comment by jarun** [comment]
The default interface is designed to use less space and so URL expansion is disabled.

To enable it by default use the option `-x`. Use and alias for example:

    alias ddgr=`ddgr -x`
