### ISSUE TITLE
Unicode error using Google bang on MacOS

### ISSUE THREAD

**Issue by magarnicle** [jarun/ddgr#93]
I installed ddgr using Homebrew on Mojave 10.14.5, with python version 3.7.4.

From the cli or omniprompt, `g! test` produces the following error:

`[ERROR] 'utf-8' codec can't decode byte 0xd7 in position 5145: invalid continuation byte
No results.`

**Comment by jarun** [comment]
Please take a look at the thread https://github.com/jarun/googler/issues/21 and see if that helps.

**Comment by jarun** [comment]
Also, please test with master.
