### ISSUE TITLE
ddr command completion script fails with syntax errors

### ISSUE THREAD

**Issue by bunyipdown** [jarun/ddgr#97]
I have ddgr installed, with bash as my login shell.
When I start a login shell, the bash completion script fails with errors: 
sh: /usr/local/etc/bash_completion.d/ddgr-completion.bashOrig: line 59: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/ddgr-completion.bashOrig: line 59: `        done < <(ddgr --complete "$cur")'
Line 59 reads:
  done < <(ddgr --complete "$cur")
I, like bash don't understand the '< <'.

ddgr command completion doesn't work, but bash can complete e.g. file names.

**Comment by jarun** [comment]
If I change it, I get an error from bash:

```
vaio @ tux  ~/GitHub/ddgr/auto-completion/bash
└─ $ ▶ . ddgr-completion.bash 
bash: ddgr-completion.bash: line 59: syntax error near unexpected token `('
bash: ddgr-completion.bash: line 59: `        done < (ddgr --complete "$cur")'
```

But in your case the error is from `sh`. Of course it doesn't understand bash syntax.

I can source the original script just fine:

```
. ddgr-completion.bash 
vaio @ tux  ~/GitHub/ddgr/auto-completion/bash
```

Your shell is still `sh`. Please fix your local env problem.

**Comment by bunyipdown** [comment]
Thanks. It was GNU screen starting sh, instead of bash.
