### ISSUE TITLE
Show only instant answers

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [jarun/ddgr#99]
A flag to only return the instant answer for the search (if any) would be nice

Simple definitions and quick answers about a topic from wikipedia are annoying to get at when being forced to either pass `-N1` and read the same text twice, or not passing any args at all and being shown 10+ results

**Comment by jarun** [comment]
Please use a local patch or an alias with `-n1` . I prefer to avoid adding a new option at this stage of the project.
